# Generated by Django 5.0.7 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_desa', models.CharField(blank=True, max_length=50, null=True)),
                ('kode_karts', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_objek', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField(blank=True, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('desa', models.CharField(blank=True, max_length=50, null=True)),
                ('dukuh', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_unik', models.CharField(blank=True, max_length=100, null=True)),
                ('letak', models.CharField(blank=True, max_length=50, null=True)),
                ('akses', models.CharField(blank=True, max_length=50, null=True)),
                ('biota', models.CharField(blank=True, max_length=50, null=True)),
                ('potensi', models.CharField(blank=True, max_length=50, null=True)),
                ('pemanfaatan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
