# Generated by Django 5.0.7 on 2024-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGoaWgs84',
            fields=[
                ('kode_desa', models.CharField(blank=True, max_length=50, null=True)),
                ('kode_karts', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_objek', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jenis', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('desa', models.CharField(blank=True, max_length=50, null=True)),
                ('dukuh', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_unik', models.CharField(blank=True, max_length=100, null=True)),
                ('letak', models.CharField(blank=True, max_length=50, null=True)),
                ('akses', models.CharField(blank=True, max_length=50, null=True)),
                ('biota', models.CharField(blank=True, max_length=50, null=True)),
                ('potensi', models.CharField(blank=True, max_length=50, null=True)),
                ('pemanfaatan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_goa_wgs84',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabelGoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='full name')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
